server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE